global:
    scrape_interval: 5s
    evaluation_interval: 5s
scrape_configs:
  - job_name: router
    scrape_interval: 10s
    static_configs:
        - targets: [ 'yourip:9001', 'yourip:9002']
    metrics_path: "/metrics"

