global:
    scrape_interval: 5s
    evaluation_interval: 5s
scrape_configs:
  - job_name: router
    scrape_interval: 10s
    static_configs:
        - targets: [ '127.0.0.1:9001', '127.0.0.1:9002']
    metrics_path: "/metrics"

